DROP TABLE IF EXISTS ORG;
CREATE TABLE ORG(ORG_ID INT PRIMARY KEY,  org_name VARCHAR(255));
INSERT INTO ORG VALUES(1, 'Bank Of America');
INSERT INTO ORG VALUES(2, 'JPMC');

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT(ACCOUNT_ID INT PRIMARY KEY,  ORG_ID INT , account_name VARCHAR(255));

ALTER TABLE ACCOUNT
    ADD FOREIGN KEY (ORG_ID) 
    REFERENCES ORG(ORG_ID);


INSERT INTO ACCOUNT VALUES(1, 1,'Account one');
INSERT INTO ACCOUNT VALUES(2, 1, 'Account two');


DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(ADDR_ID INT PRIMARY KEY,  ORG_ID INT , street_address VARCHAR(255));

ALTER TABLE ADDRESS
    ADD FOREIGN KEY (ORG_ID) 
    REFERENCES ORG(ORG_ID);


INSERT INTO ADDRESS VALUES(1, 1,'Address one');
INSERT INTO ADDRESS VALUES(2, 1, 'Address two');
